### ISSUE TITLE
rpg_common not available

### ISSUE THREAD

**Issue by aydal** [uzh-rpg/sim2real_drone_racing#1]
Hello guys.
Real amazing work on the paper. I wanted to check the code fo some random environments but faced following issues

1. The syntax for git clone doesn't work. Needs some keys or something. Or edit to the  conventional method
2. Cannot find repo rpg_common.  Has it been replaced by something else?

**Comment by antonilo** [comment]
@aydal Thanks for your feedback! We have fixed this problem in #2 .

**Comment by antonilo** [comment]
Closing the issue if there is no further problem.
